### PR TITLE
Support perls which do not provide . in @INC by default for Makefile.PL

### PR DESCRIPTION
**Pull request by toddr**

### CODE REVIEW

**Comment by rehsack** [comment]
I fear this isn't necessary anymore :(

**Comment by toddr** [comment]
This is still necessary. If perl is built without . in @INC, it cannot load modules from a relative directory.

As of 5.25.9 you can build such a perl by using the Configure option -Ddefault_inc_excludes_dot 

```
$>perl Makefile.PL 
Can't locate inc/Config/AutoConf/LMU.pm in @INC (you may need to install the inc::Config::AutoConf::LMU module) (@INC contains: /perl/5.25.9/lib/site_perl/5.25.9/x86_64-linux /perl/5.25.9/lib/site_perl/5.25.9 /perl/5.25.9/lib/5.25.9/x86_64-linux /perl/5.25.9/lib/5.25.9) at Makefile.PL line 65.
BEGIN failed--compilation aborted at Makefile.PL line 65.

**Comment by rehsack** [comment]
In the new Makefile.PL at line 65 is nothing which could explain your error message. Did you "git pull" before complaining?

**Comment by kentfredric** [comment]
> This is still necessary

I suspect rehsack was saying "fixed in git"

But it has yet to be fixed on CPAN.

**Comment by rehsack** [comment]
Is this an RT ticket? Or is it a pull request against the source code repository?
Don't try interpret a clear thing.

**Comment by kentfredric** [comment]
I don't understand. Either way, when its fixed on CPAN, feel free to respond so we can test it && etc.

**Comment by rehsack** [comment]
Than please either test the git checkout - or if you can't do, add yourself at Sawyer's RT (https://rt.cpan.org/Ticket/Display.html?id=117036) and move your ass out of a PR

**Comment by toddr** [comment]
@rehsack , I've reviewed the branch as you have it. Before I open tickets, I thought I'd try here first.

1. perl Makfile.PL fails on the git checkout. I worked around this by doing make dist.
``` shell
$>perl Makefile.PL
Can't locate Sandbox/Tumble.pm in @INC (you may need to install the Sandbox::Tumble module) (@INC contains: /perl/5.25.9/lib/site_perl/5.25.9/x86_64-linux /perl/5.25.9/lib/site_perl/5.25.9 /perl/5.25.9/lib/5.25.9/x86_64-linux /perl/5.25.9/lib/5.25.9) at (eval 16) line 1.
BEGIN failed--compilation aborted at (eval 16) line 1.
```

2. MANIFEST is now gone and also files in t. How do I do make test?

Beyond the above I seem to be able to do perl Makefile.PL && make install with what I was able to put together.

Not sure what your final tarball will look like. Would you mind uploading it to pause so I can verify?

Thanks,
Todd

**Comment by rehsack** [comment]
@toddr - thanks for investing the time.
I made some other mistakes together with that - unfortunately I'm low on tuits at the very moment.
Have a look at .travis.yml to have an impression how to make test (and yes, you're right then, I forgot the lines 8..14 from L::MU::XS's Makefile.PL (or you're patch).

It's not that much here and I try to manage it before Eastern.

Cheers,
Jens

**Comment by toddr** [comment]
@rehsack We're discussing removing . from @INC in 5.25.11 right now. How can I help. Do you want a pull  request? Do you want to give co-maint? I need another module like a hole in the head but I'm happy to help to fast track a release.

**Comment by haarg** [comment]
@rehsack Would it be possible to do a release with just this PR (or something similar) included and leave the refactoring work you are doing until later?  There are a few other issues I noticed with the XS/PP split that should be addressed before a release is done, but this patch should be low impact and relieve any pressure to rush the refactoring work.

**Comment by rehsack** [comment]
Gimme until end of week, I do my best.
Co-Maint requires reasonable pull-requests, sorry.

**Comment by rehsack** [comment]
Hacked, pushed, run through travis ... if I don't hear bad things until tomorrow, I will try to release a DEV release and shortly after the XS one (with harmonized Makefile.PL)...

**Pull request closed without merging**
