### PR TITLE
add part_hash

### PR DESCRIPTION
**Pull request by yanick**
Just like 'part', but returns pairs of keys/values.

### CODE REVIEW

**Comment by rehsack** [comment]
This patch fails all tests. Would you please investigate to fix the failures?

**Comment by yanick** [comment]
Ooops. Typo in the test's `substr` call. After this fix, all but the xt tests pass. (at least for me)

**Comment by rehsack** [comment]
Can you do the fix as an amended commit? (read: avoid "fix typo" commits)

**Comment by yanick** [comment]
Done.

**Comment by yanick** [comment]
Hmmm... The travis builds  that are failing are for osx, and they're complaining that... cpanm can't be found? O.o

**Comment by rehsack** [comment]
Last time I looked all travis builds fail - and it wasn't that obvious ;)
I rate that as "Travis problems" and go ahead.

**Comment by yanick** [comment]
On 2015-10-13 07:42 AM, Jens Rehsack wrote:
> Last time I looked all travis builds fail - and it wasn't that obvious ;)
> I rate that as "Travis problems" and go ahead.

Weeeeee! \o/

**Comment by rehsack** [comment]
@yanick - please excuse delay caused by me. Would you agree that this function is placed better in https://github.com/perl5-utils/Hash-MoreUtils ?

**Comment by yanick** [comment]
@rehsack Sure. I think I went for A::MU because all functions in H::MU are done on hashes, and the argument of part_hash is an array, but that works too.

If we move the function there, its name should probably be changed to `hash_part` (or simply `aggregate`?) to keep with the local names.

**Comment by rehsack** [comment]
Yeah, it's somehow a hybrid - I'm torn ...

**Comment by yanick** [comment]
On 2016-04-15 10:21 AM, Jens Rehsack wrote:
> Yeah, it's somehow a hybrid - I'm torn ...

Go for Hash::MU. :-)

**Comment by xdg** [comment]
Could call it `part_key` or `part_kv` or something.

If the input is a list, then I think it fits here.  There's nothing about this that consumes or produces a hash.  That you can assign the resulting list to a hash is a feature of perl, not this module.

**Comment by rehsack** [comment]
Currently it's the first function returning a hash ...
Unfortunately it requires dedicated hash support (strings can't be used as array index) ...

But I agree - it works on a list, so it is a list tool.

For naming - is `part_map` reasonable?

**Comment by yanick** [comment]
On 2016-04-16 07:44 AM, Jens Rehsack wrote:
> For naming - is |part_map| reasonable?

I think it is. I first went with 'hashgregate', but the portmanteau name
made people physically ill... I then went for "part_hash" to reflect
it's a sibling to the already existing 'part'. `part_map` is a perfectly
good variation on that theme. Other possible names on top of my head:
`aggregate`, `group_by`.

**Comment by yanick** [comment]
Found that it already exists as `partition_by` in List::UtilsB: https://metacpan.org/pod/List::UtilsBy#partition_by

Considering that it's already out there, I think this PR can be closed.

**Pull request closed without merging**
